"""
app/ai/security_analyst.py
───────────────────────────
AI-powered security analysis, education, and remediation services.

Uses the local Ollama/Qwen client for threat explanations, security Q&A,
and remediation plans. Every method degrades gracefully to
rule-based fallbacks when the LLM is unavailable.

The AI NEVER helps bypass security — it only explains, educates, and
guides remediation.
"""

from __future__ import annotations

import asyncio
import json
import logging
from dataclasses import dataclass, field
from typing import Any

from app.ai.local_llm_client import (
    LocalLLMClient,
    LocalLLMUnavailableError,
    local_llm_client as local_llm_client_singleton,
)
from app.threat_engine.scorer import ThreatAssessment

logger = logging.getLogger("rasp.ai.analyst")


# ═══════════════════════════════════════════════════════════════════════
# Data Transfer Objects
# ═══════════════════════════════════════════════════════════════════════

@dataclass
class ThreatExplanation:
    """Structured explanation of a threat assessment.

    Attributes
    ----------
    title : str
        Short headline (max ~10 words).
    explanation : str
        Plain-English, non-technical explanation.
    technical_detail : str
        Technical explanation for advanced users.
    recommendation : list[str]
        3-5 actionable remediation steps.
    severity_reason : str
        Why this specific combination warrants its risk level.
    source : str
        ``"llm"`` when generated by the local model, ``"rule_based"`` on fallback.
    """

    title: str = ""
    explanation: str = ""
    technical_detail: str = ""
    recommendation: list[str] = field(default_factory=list)
    severity_reason: str = ""
    source: str = "rule_based"


@dataclass
class RemediationStep:
    """A single step in a remediation plan.

    Attributes
    ----------
    step_number : int
        Ordinal position.
    action : str
        Short action label.
    description : str
        Full description of what to do.
    difficulty : str
        ``"easy"`` | ``"moderate"`` | ``"advanced"``.
    """

    step_number: int = 0
    action: str = ""
    description: str = ""
    difficulty: str = "easy"


@dataclass
class RemediationPlan:
    """Complete remediation plan for detected threats.

    Attributes
    ----------
    steps : list[dict]
        Ordered list of remediation step dictionaries.
    estimated_time : str
        Human-readable time estimate (e.g. "5 minutes").
    requires_technical_knowledge : bool
        Whether the steps need advanced user skills.
    priority : str
        ``"IMMEDIATE"`` | ``"HIGH"`` | ``"NORMAL"``.
    """

    steps: list[dict[str, Any]] = field(default_factory=list)
    estimated_time: str = "5 minutes"
    requires_technical_knowledge: bool = False
    priority: str = "NORMAL"


# ═══════════════════════════════════════════════════════════════════════
# System Prompts
# ═══════════════════════════════════════════════════════════════════════

_SYSTEM_THREAT_ANALYSIS = (
    "You are a mobile security expert assistant. You explain security threats "
    "in simple, non-technical language first, then provide technical details. "
    "You NEVER help users bypass security systems. You ONLY explain, educate, "
    "and guide remediation. Keep responses concise and structured."
)

_SYSTEM_SECURITY_EDUCATOR = (
    "You are a mobile security educator. Answer security questions clearly:\n"
    "1. Start with a simple, non-technical explanation (1-2 sentences).\n"
    "2. Provide technical details (2-3 sentences).\n"
    "3. Explain why it matters for mobile app security (1-2 sentences).\n"
    "Keep total response under 200 words. Be factual and helpful."
)

_SYSTEM_REMEDIATION = (
    "You are a mobile security remediation specialist. Generate step-by-step "
    "remediation plans for detected mobile security threats. Respond ONLY with "
    "valid JSON. No markdown. No extra text."
)

# ── Context injection for known topics ────────────────────────────────
_TOPIC_CONTEXT: dict[str, str] = {
    "frida": (
        "Context: Frida is a dynamic instrumentation toolkit used by security "
        "researchers and attackers. It allows injecting JavaScript into running "
        "apps to intercept function calls, modify data, and bypass security checks."
    ),
    "root": (
        "Context: Rooting (Android) or jailbreaking (iOS) grants superuser "
        "privileges, bypassing OS security boundaries. Rooted devices can run "
        "apps with full system access, making them vulnerable to data theft."
    ),
    "block": (
        "Context: A device may be blocked when its cumulative risk score exceeds "
        "thresholds, indicating persistent tampering, instrumentation, or malware."
    ),
    "emulator": (
        "Context: Emulators are software-based virtual devices. Attackers use "
        "them to clone apps, automate fraud, replay transactions, or reverse-engineer "
        "app logic without physical hardware."
    ),
    "mitm": (
        "Context: A Man-in-the-Middle (MITM) attack intercepts network traffic "
        "between a mobile app and its server. Attackers can read, modify, or inject "
        "data by using proxy tools like mitmproxy or Charles Proxy."
    ),
}

_CHAT_TIMEOUT_SECONDS = 60.0

# ═══════════════════════════════════════════════════════════════════════
# Threat-specific fallback data
# ═══════════════════════════════════════════════════════════════════════

_THREAT_DESCRIPTIONS: dict[str, dict[str, str]] = {
    "root_detected": {
        "label": "Root/Jailbreak",
        "explanation": "Your device has elevated privileges that bypass normal security restrictions.",
        "technical": "Root access grants uid 0 (superuser), allowing unrestricted file-system access and process control.",
        "action": "Use an unrooted device for sensitive applications.",
    },
    "frida_detected": {
        "label": "Dynamic Instrumentation (Frida)",
        "explanation": "A tool that can modify app behaviour at runtime has been detected on your device.",
        "technical": "Frida injects a JavaScript engine into the app process, hooking native and JVM functions.",
        "action": "Remove Frida server and related tools from the device.",
    },
    "debugger_detected": {
        "label": "Debugger Attached",
        "explanation": "A debugging tool is attached to the app, which could let someone inspect sensitive data.",
        "technical": "JDWP or ptrace-based debugger detected on the application process.",
        "action": "Disconnect any debugging tools and restart the application.",
    },
    "tamper_detected": {
        "label": "App Tampering",
        "explanation": "The application has been modified from its original version.",
        "technical": "APK/IPA signature verification failed, indicating binary modification or repackaging.",
        "action": "Reinstall the app from the official app store.",
    },
    "emulator_detected": {
        "label": "Emulator Environment",
        "explanation": "The app is running on a virtual device instead of real hardware.",
        "technical": "Emulator fingerprints detected (generic hardware IDs, QEMU/VBox artifacts).",
        "action": "Run the app on a physical device for full functionality.",
    },
    "vpn_detected": {
        "label": "VPN Connection",
        "explanation": "A VPN is routing your network traffic through a third-party server.",
        "technical": "Active TUN/TAP interface or VPN service detected in the network stack.",
        "action": "If not intentional, disconnect the VPN before using the app.",
    },
    "proxy_detected": {
        "label": "Network Proxy",
        "explanation": "A proxy is intercepting your network requests, which could expose data.",
        "technical": "HTTP(S) proxy configuration or certificate pinning bypass detected.",
        "action": "Remove any proxy configuration from device network settings.",
    },
    "overlay_detected": {
        "label": "Screen Overlay",
        "explanation": "Another app is drawing on top of this app, which could capture your input.",
        "technical": "TYPE_APPLICATION_OVERLAY or SYSTEM_ALERT_WINDOW permission in use by another process.",
        "action": "Disable overlay permissions for untrusted apps in system settings.",
    },
    "accessibility_abuse": {
        "label": "Accessibility Service Abuse",
        "explanation": "An accessibility service may be reading or controlling this app without your knowledge.",
        "technical": "AccessibilityService bound to the app process with broad event types.",
        "action": "Review and disable unnecessary accessibility services.",
    },
    "hook_detected": {
        "label": "Function Hooking",
        "explanation": "App functions are being intercepted and potentially modified by external code.",
        "technical": "Inline hooks, PLT/GOT modifications, or Xposed framework modules detected.",
        "action": "Uninstall hooking frameworks (Xposed, LSPosed) and restart the device.",
    },
    "location_spoof": {
        "label": "Location Spoofing",
        "explanation": "Your device location appears to be faked by a mock-location app.",
        "technical": "Mock location provider enabled or GPS coordinates inconsistent with network location.",
        "action": "Disable mock location in developer options.",
    },
    "time_spoof": {
        "label": "Time Manipulation",
        "explanation": "The device clock has been tampered with, which could bypass time-based security.",
        "technical": "System clock deviation exceeds threshold compared to NTP reference.",
        "action": "Enable automatic date & time in system settings.",
    },
    "malware_detected": {
        "label": "Malware Detected",
        "explanation": "Potentially malicious software has been found on your device.",
        "technical": "Known malware signatures or suspicious app behaviour patterns identified.",
        "action": "Run a full device scan with a reputable antivirus and remove flagged apps.",
    },
    "screenshot_detected": {
        "label": "Screenshot Capture",
        "explanation": "A screenshot or screen recording of the app was detected.",
        "technical": "Screen capture callback triggered or screencap service activity detected.",
        "action": "Be cautious about sensitive information visible on screen.",
    },
}


# ═══════════════════════════════════════════════════════════════════════
# SecurityAnalystAI
# ═══════════════════════════════════════════════════════════════════════

class SecurityAnalystAI:
    """AI-powered security analysis, education, and remediation.

    Uses local Qwen for rich natural-language output and falls
    back to deterministic rule-based responses when the LLM is unavailable.

    Parameters
    ----------
    llm_client : LocalLLMClient | None
        Injected client; uses the singleton local client when ``None``.
    """

    def __init__(self, llm_client: LocalLLMClient | None = None) -> None:
        """Initialise the analyst with a local LLM client."""
        self.llm = llm_client or local_llm_client_singleton

    # ── METHOD 1: explain_threat ──────────────────────────────────────

    async def explain_threat(self, assessment: ThreatAssessment) -> ThreatExplanation:
        """Generate a structured explanation for a threat assessment.

        Sends the assessment details to the LLM with a carefully engineered
        prompt and parses the JSON response.  Falls back to rule-based
        output when the LLM is unavailable or returns unparseable content.

        Parameters
        ----------
        assessment : ThreatAssessment
            Output from :py:meth:`ThreatScorer.calculate`.

        Returns
        -------
        ThreatExplanation
            Structured explanation with title, explanation, technical
            detail, recommendations, and severity reasoning.
        """
        if not assessment.active_threats:
            return ThreatExplanation(
                title="All Clear",
                explanation="No security threats were detected on this device.",
                technical_detail="All RASP checks passed without triggering any threat signals.",
                recommendation=["Continue using the app normally.", "Keep your device updated."],
                severity_reason="No threats detected, risk score is zero.",
                source="rule_based",
            )

        prompt = (
            f"A mobile device reported the following security threats:\n"
            f"Active threats: {', '.join(assessment.active_threats)}\n"
            f"Risk score: {assessment.score}\n"
            f"Risk level: {assessment.level}\n\n"
            f"Provide a JSON response with exactly these keys:\n"
            f'- "title": short threat title (max 10 words)\n'
            f'- "explanation": plain English explanation (2-3 sentences, non-technical first)\n'
            f'- "technical_detail": technical explanation (2-3 sentences)\n'
            f'- "recommendation": list of 3-5 actionable steps the user should take\n'
            f'- "severity_reason": why this specific combination warrants the risk level\n\n'
            f"Respond ONLY with valid JSON. No markdown. No extra text."
        )

        try:
            raw = await self.llm.generate(prompt=prompt, system=_SYSTEM_THREAT_ANALYSIS, temperature=0.3)
            parsed = self._parse_json_response(raw)

            if parsed:
                return ThreatExplanation(
                    title=parsed.get("title", assessment.summary[:60]),
                    explanation=parsed.get("explanation", ""),
                    technical_detail=parsed.get("technical_detail", ""),
                    recommendation=parsed.get("recommendation", []),
                    severity_reason=parsed.get("severity_reason", ""),
                    source="llm",
                )
        except LocalLLMUnavailableError:
            logger.warning("Local LLM unavailable — using rule-based threat explanation")
        except Exception as exc:
            logger.error("Error during LLM threat explanation: %s", exc, exc_info=True)

        # ── Rule-based fallback ───────────────────────────────────────
        return self._rule_based_explanation(assessment)

    # ── METHOD 2: answer_security_question ────────────────────────────

    async def answer_security_question(
        self,
        question: str,
        context: dict[str, Any] | None = None,
    ) -> str:
        """Answer a user's security question using the LLM.

        Injects relevant topic context for known subjects (Frida, rooting,
        MITM, etc.) and falls back to a canned response when the local LLM is
        unavailable.

        Parameters
        ----------
        question : str
            The user's question text.
        context : dict | None
            Optional extra context (e.g. current device threat status).

        Returns
        -------
        str
            The AI-generated (or rule-based fallback) answer.
        """
        # ── Inject topic-specific context ─────────────────────────────
        extra_context = ""
        question_lower = question.lower()
        for keyword, ctx_text in _TOPIC_CONTEXT.items():
            if keyword in question_lower:
                extra_context += f"\n{ctx_text}"

        if context:
            extra_context += f"\nDevice context: {json.dumps(context, default=str)}"

        prompt = question
        if extra_context:
            prompt = f"{extra_context}\n\nUser question: {question}"

        try:
            return await asyncio.wait_for(
                self.llm.generate(
                    prompt=prompt,
                    system=_SYSTEM_SECURITY_EDUCATOR,
                    temperature=0.35,
                    max_tokens=192,
                ),
                timeout=_CHAT_TIMEOUT_SECONDS,
            )
        except LocalLLMUnavailableError:
            logger.warning("Local LLM unavailable — using rule-based chat response")
            return self._rule_based_answer(question)
        except asyncio.TimeoutError:
            logger.warning("Local LLM chat timed out — using rule-based chat response")
            return self._rule_based_answer(question)
        except Exception as exc:
            logger.error("Error during LLM chat: %s", exc, exc_info=True)
            return self._rule_based_answer(question)

    # ── METHOD 3: generate_remediation_plan ───────────────────────────

    async def generate_remediation_plan(self, threats: list[str]) -> RemediationPlan:
        """Generate a step-by-step remediation plan for active threats.

        Attempts LLM generation first, falls back to curated rule-based
        steps per threat type.

        Parameters
        ----------
        threats : list[str]
            Names of active threat signals.

        Returns
        -------
        RemediationPlan
            Ordered steps, time estimate, difficulty, and priority.
        """
        if not threats:
            return RemediationPlan(
                steps=[{
                    "step_number": 1,
                    "action": "No action needed",
                    "description": "No threats detected. Continue using the app normally.",
                    "difficulty": "easy",
                }],
                estimated_time="0 minutes",
                requires_technical_knowledge=False,
                priority="NORMAL",
            )

        prompt = (
            f"Generate a remediation plan for these mobile security threats: {', '.join(threats)}\n\n"
            f"Respond with a JSON object containing exactly these keys:\n"
            f'- "steps": list of objects with keys "step_number", "action", "description", "difficulty"\n'
            f'  (difficulty is one of: "easy", "moderate", "advanced")\n'
            f'- "estimated_time": string (e.g. "5 minutes")\n'
            f'- "requires_technical_knowledge": boolean\n'
            f'- "priority": one of "IMMEDIATE", "HIGH", "NORMAL"\n\n'
            f"Respond ONLY with valid JSON. No markdown. No extra text."
        )

        try:
            raw = await self.llm.generate(prompt=prompt, system=_SYSTEM_REMEDIATION, temperature=0.3)
            parsed = self._parse_json_response(raw)
            if parsed and "steps" in parsed:
                return RemediationPlan(
                    steps=parsed.get("steps", []),
                    estimated_time=parsed.get("estimated_time", "10 minutes"),
                    requires_technical_knowledge=parsed.get("requires_technical_knowledge", False),
                    priority=parsed.get("priority", "NORMAL"),
                )
        except LocalLLMUnavailableError:
            logger.warning("Local LLM unavailable — using rule-based remediation plan")
        except Exception as exc:
            logger.error("Error during LLM remediation plan: %s", exc, exc_info=True)

        return self._rule_based_remediation(threats)

    # ── Generate suggested follow-up questions ────────────────────────

    async def generate_follow_up_questions(
        self,
        user_message: str,
        ai_response: str,
    ) -> list[str]:
        """Generate three suggested follow-up questions.

        Attempts LLM generation; returns curated defaults on failure.

        Parameters
        ----------
        user_message : str
            The user's original question.
        ai_response : str
            The AI's answer to the question.

        Returns
        -------
        list[str]
            Three follow-up questions the user might ask next.
        """
        return [
            "How can I protect my device from this threat?",
            "What are the signs of a compromised device?",
            "Should I reinstall the app to be safe?",
        ]

    # ── Private helpers ───────────────────────────────────────────────

    @staticmethod
    def _parse_json_response(raw: str) -> Any:
        """Attempt to parse an LLM response as JSON.

        Handles common LLM quirks like wrapping in code fences.

        Parameters
        ----------
        raw : str
            Raw text from the LLM.

        Returns
        -------
        dict | list | None
            Parsed JSON or ``None`` on failure.
        """
        text = raw.strip()
        # Strip markdown code fences if present
        if text.startswith("```"):
            lines = text.split("\n")
            text = "\n".join(lines[1:])
            if text.endswith("```"):
                text = text[:-3]
            text = text.strip()

        try:
            return json.loads(text)
        except json.JSONDecodeError:
            # Try to find JSON object or array in the text
            for start_char, end_char in [("{", "}"), ("[", "]")]:
                start = text.find(start_char)
                end = text.rfind(end_char)
                if start != -1 and end != -1 and end > start:
                    try:
                        return json.loads(text[start : end + 1])
                    except json.JSONDecodeError:
                        continue
            logger.warning("Failed to parse LLM JSON response: %s", text[:200])
            return None

    @staticmethod
    def _rule_based_explanation(assessment: ThreatAssessment) -> ThreatExplanation:
        """Build a ThreatExplanation from curated threat descriptions.

        Parameters
        ----------
        assessment : ThreatAssessment
            The scored assessment to explain.

        Returns
        -------
        ThreatExplanation
            Deterministic, rule-based explanation.
        """
        explanations: list[str] = []
        technical_parts: list[str] = []
        recommendations: list[str] = []

        for threat in assessment.active_threats:
            info = _THREAT_DESCRIPTIONS.get(threat, {})
            if info:
                explanations.append(info.get("explanation", ""))
                technical_parts.append(info.get("technical", ""))
                recommendations.append(info.get("action", ""))

        # Build title from top threats
        labels = [
            _THREAT_DESCRIPTIONS.get(t, {}).get("label", t.replace("_", " ").title())
            for t in assessment.active_threats[:3]
        ]
        title = " + ".join(labels) + " Detected"

        return ThreatExplanation(
            title=title[:80],
            explanation=" ".join(explanations) if explanations else assessment.summary,
            technical_detail=" ".join(technical_parts) if technical_parts else "Multiple RASP checks triggered.",
            recommendation=recommendations if recommendations else ["Contact your IT security team."],
            severity_reason=(
                f"Combined risk score of {assessment.score} ({assessment.level}) indicates "
                f"{'critical security compromise requiring immediate attention' if assessment.level == 'CRITICAL' else 'elevated risk that should be addressed'}."
            ),
            source="rule_based",
        )

    @staticmethod
    def _rule_based_answer(question: str) -> str:
        """Provide a canned answer for common security questions.

        Parameters
        ----------
        question : str
            The user's question text.

        Returns
        -------
        str
            A rule-based answer string.
        """
        q = question.lower()
        if "frida" in q:
            return (
                "Frida is a security testing tool that can modify how apps work while they're running. "
                "Technically, it injects a JavaScript engine into app processes to intercept and alter "
                "function calls. If Frida is detected on your device, it could mean someone is trying "
                "to bypass the app's security protections. You should remove any Frida-related software "
                "from your device."
            )
        if "root" in q or "jailbreak" in q:
            return (
                "Rooting (Android) or jailbreaking (iOS) means giving yourself superuser access to "
                "your device's operating system. While this gives more control, it also removes "
                "important security barriers. Rooted devices are more vulnerable to malware and "
                "data theft because apps can access protected system files. For best security, "
                "use an unrooted device."
            )
        if "emulator" in q or "virtual" in q:
            return (
                "An emulator is software that mimics a physical phone on a computer. While useful "
                "for development, attackers use emulators to clone apps, automate fraudulent "
                "transactions, or reverse-engineer app logic. Our RASP system detects emulators "
                "to prevent these abuse scenarios."
            )
        if "mitm" in q or "man in the middle" in q or "proxy" in q:
            return (
                "A Man-in-the-Middle (MITM) attack happens when someone secretly intercepts the "
                "communication between your app and the server. Using proxy tools, an attacker can "
                "read, modify, or inject data into your network traffic. VPN and proxy detection "
                "helps identify potential MITM setups. Always use trusted networks and verify your "
                "network settings."
            )
        if "block" in q:
            return (
                "Your device may be blocked if our security system detected persistent or severe "
                "threats like rooting combined with instrumentation tools. Blocking protects your "
                "account from potential compromise. To regain access, remove any security threats "
                "and contact support."
            )
        return (
            "That's a great security question. While I can't provide a detailed AI-generated "
            "answer right now (the AI service is temporarily unavailable), I recommend consulting "
            "your organization's security team or visiting OWASP Mobile Security resources at "
            "https://owasp.org/www-project-mobile-security/ for comprehensive guidance."
        )

    @staticmethod
    def _rule_based_remediation(threats: list[str]) -> RemediationPlan:
        """Build a remediation plan from curated per-threat steps.

        Parameters
        ----------
        threats : list[str]
            List of active threat names.

        Returns
        -------
        RemediationPlan
            Deterministic remediation plan with ordered steps.
        """
        steps: list[dict[str, Any]] = []
        has_advanced = False
        step_num = 0

        for threat in threats:
            info = _THREAT_DESCRIPTIONS.get(threat, {})
            step_num += 1
            difficulty = "advanced" if threat in ("root_detected", "frida_detected", "hook_detected", "malware_detected") else "easy"
            if difficulty == "advanced":
                has_advanced = True
            steps.append({
                "step_number": step_num,
                "action": f"Address {info.get('label', threat.replace('_', ' '))}",
                "description": info.get("action", "Investigate and resolve this threat."),
                "difficulty": difficulty,
            })

        # Final verification step
        step_num += 1
        steps.append({
            "step_number": step_num,
            "action": "Verify Resolution",
            "description": "Restart the app and check if the security warnings are resolved.",
            "difficulty": "easy",
        })

        high_severity = any(t in ("root_detected", "frida_detected", "malware_detected", "hook_detected") for t in threats)

        return RemediationPlan(
            steps=steps,
            estimated_time=f"{len(threats) * 5} minutes",
            requires_technical_knowledge=has_advanced,
            priority="IMMEDIATE" if high_severity else ("HIGH" if len(threats) > 2 else "NORMAL"),
        )
